Docker hosting update
Coder-Tavi/Voraphiliac pull request #22
Opened 2022-09-15 23:47 UTC by FlipperLP

2022-09-15 23:55 UTC, Coder-Tavi requested changes
See my comments. Need those fixed first

2022-09-15 23:55 UTC, Coder-Tavi commented on configs/dist.responces.json
> +{
responses*

2022-09-15 23:55 UTC, Coder-Tavi commented on README.md
> -**This bot is in the "fast development" stage meaning changes will be made rapidly. Please do not expect any current features to remain the same until V1.0.0 is released. The current version is V0.X*
Please leave this note in. I will remove it manually when I exit the fast dev stage

2022-09-15 23:55 UTC, Coder-Tavi commented on package.json
> +  "description": "**This bot is in the \"fast development\" stage meaning changes will be made rapidly. Please do not expect any current features to remain the same until V1.0.0 is released. The curr
Swap this to "Vore bot that utilizes Discord's Interaction system for a unique experiment"

2022-09-15 23:57 UTC, FlipperLP commented on README.md
> -**This bot is in the "fast development" stage meaning changes will be made rapidly. Please do not expect any current features to remain the same until V1.0.0 is released. The current version is V0.X*
it is left in. its further down and has its own section. Title needs to be at the top, because MD violation

2022-09-16 00:08 UTC, Coder-Tavi commented on package.json
> +  "description": "Vore bot that utilizes Discord's Interaction system for a unique experiment.",
I am so sorry but can you rewrite it from "unique experiment" to "unique experience"? My brain turned off then

2022-09-16 00:09 UTC, Coder-Tavi commented on package.json
> +    "url": "git+https://github.com/Coder-Tavi/Voraphiliac.git"
Tryna steal credit from me :P

2022-09-16 00:09 UTC, Coder-Tavi reviewed
One last thing

2022-09-16 00:17 UTC, FlipperLP commented
you do know, you can also edit ^^

2022-09-16 00:38 UTC, Coder-Tavi approved these changes
All fixed!

2022-09-16 00:38 UTC, merged